#!/usr/bin/env python3
"""Generates Talkflow.Core/Text/EmojiMap.g.cs from the Mac app's TextCommands.swift.

The emoji names and aliases are data, and the Windows app must resolve exactly
the same spoken names as the Mac. Copying them by hand would drift, so the C#
table is generated from the Swift source and CI fails when the two disagree:

    python3 windows/tools/gen_emoji.py          # rewrite the C# file
    python3 windows/tools/gen_emoji.py --check  # exit 1 if it is out of date
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "Sources/talkflowd/TextCommands.swift"
OUT = ROOT / "windows/Talkflow.Core/Text/EmojiMap.g.cs"


def literal(source: str, name: str) -> list[tuple[str, str]]:
    start = source.index(f"static let {name}: [String: String] = [")
    body = source[source.index("[", source.index("=", start)) + 1:]
    depth, end = 1, 0
    for i, ch in enumerate(body):
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                end = i
                break
    body = body[:end]
    body = re.sub(r"//[^\n]*", "", body)
    return re.findall(r'"((?:[^"\\]|\\.)*)"\s*:\s*"((?:[^"\\]|\\.)*)"', body)


def csharp(value: str) -> str:
    out = []
    for ch in value:
        if ch in '"\\':
            out.append("\\" + ch)
        elif ord(ch) < 0x80:
            out.append(ch)
        elif ord(ch) <= 0xFFFF:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(f"\\U{ord(ch):08X}")
    return '"' + "".join(out) + '"'


def render() -> str:
    source = SWIFT.read_text(encoding="utf-8")
    lines = [
        "// <auto-generated>",
        "// Generated by windows/tools/gen_emoji.py from Sources/talkflowd/TextCommands.swift.",
        "// Do not edit by hand: change the Swift table and run the script.",
        "// </auto-generated>",
        "using System.Collections.Generic;",
        "",
        "namespace Talkflow.Core.Text;",
        "",
        "public static partial class TextCommands",
        "{",
    ]
    for name, field in (("emojiMap", "EmojiMap"), ("emojiAliases", "EmojiAliases")):
        pairs = literal(source, name)
        keys = [k for k, _ in pairs]
        if len(keys) != len(set(keys)):
            sys.exit(f"duplicate key in {name}")
        lines.append(f"    public static readonly IReadOnlyDictionary<string, string> {field} = new Dictionary<string, string>")
        lines.append("    {")
        for key, value in pairs:
            lines.append(f"        [{csharp(key)}] = {csharp(value)},")
        lines.append("    };")
        lines.append("")
    lines[-1] = "}"
    return "\n".join(lines) + "\n"


def main() -> None:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is out of date: run python3 windows/tools/gen_emoji.py")
        print("emoji table matches TextCommands.swift")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
